import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const upstreamRoot = join(root, 'artifacts', 'p0', 'upstream');
const evidencePath = join(root, 'artifacts', 'p0', 'dependency-evidence.json');
const verified = process.argv.includes('--verified');

const sources = [
  {
    id: 'uniswap-v3-factory',
    packageName: '@uniswap/v3-core',
    version: '1.0.1',
    artifact: 'artifacts/contracts/interfaces/IUniswapV3Factory.sol/IUniswapV3Factory.json',
    solidity: 'contracts/interfaces/IUniswapV3Factory.sol',
    license: 'LICENSE',
    output: 'src/protocols/uniswap-v3/abi.ts',
    exportName: 'v3FactoryAbi',
    sourceUrl: 'https://unpkg.com/@uniswap/v3-core@1.0.1/contracts/interfaces/IUniswapV3Factory.sol',
  },
  {
    id: 'uniswap-v3-pool',
    packageName: '@uniswap/v3-core',
    version: '1.0.1',
    artifact: 'artifacts/contracts/interfaces/IUniswapV3Pool.sol/IUniswapV3Pool.json',
    solidity: 'contracts/interfaces/IUniswapV3Pool.sol',
    license: 'LICENSE',
    output: 'src/protocols/uniswap-v3/abi.ts',
    exportName: 'v3PoolAbi',
    sourceUrl: 'https://unpkg.com/@uniswap/v3-core@1.0.1/contracts/interfaces/IUniswapV3Pool.sol',
  },
  {
    id: 'uniswap-v4-manager',
    packageName: '@uniswap/v4-core',
    version: '1.0.2',
    artifact: 'out/IPoolManager.sol/IPoolManager.json',
    solidity: 'src/interfaces/IPoolManager.sol',
    license: 'licenses/MIT_LICENSE',
    output: 'src/protocols/uniswap-v4/abi.ts',
    exportName: 'v4ManagerAbi',
    sourceUrl: 'https://unpkg.com/@uniswap/v4-core@1.0.2/src/interfaces/IPoolManager.sol',
  },
];

const sha256 = (contents) => createHash('sha256').update(contents).digest('hex');
const packageRoot = (packageName) => join(root, 'node_modules', ...packageName.split('/'));
const readPackage = async (packageName) => JSON.parse(await readFile(join(packageRoot(packageName), 'package.json'), 'utf8'));

async function copyUpstream(source, path, label) {
  const contents = await readFile(path);
  const target = join(upstreamRoot, source.id, label);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, contents);
  return { path: relative(root, target).replaceAll('\\', '/'), sha256: sha256(contents) };
}

async function main() {
  const grouped = new Map();
  const evidence = [];

  for (const source of sources) {
    const installed = await readPackage(source.packageName);
    if (installed.version !== source.version) {
      throw new Error(`${source.packageName} must be exactly ${source.version}, found ${installed.version}`);
    }
    const sourceRoot = packageRoot(source.packageName);
    const artifactPath = join(sourceRoot, source.artifact);
    const artifactContents = await readFile(artifactPath);
    const artifact = JSON.parse(artifactContents);
    if (!Array.isArray(artifact.abi)) throw new Error(`${source.id} artifact has no ABI array`);

    const [artifactCopy, solidityCopy, licenseCopy] = await Promise.all([
      copyUpstream(source, artifactPath, 'artifact.json'),
      copyUpstream(source, join(sourceRoot, source.solidity), 'source.sol'),
      copyUpstream(source, join(sourceRoot, source.license), 'NOTICE_OR_LICENSE'),
    ]);
    const line = `export const ${source.exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const satisfies Abi;`;
    grouped.set(source.output, [...(grouped.get(source.output) ?? []), line]);
    evidence.push({
      id: source.id,
      package: source.packageName,
      version: installed.version,
      packageLicense: installed.license ?? null,
      sourceUrl: source.sourceUrl,
      sourceSpdx: (await readFile(join(sourceRoot, source.solidity), 'utf8')).match(/SPDX-License-Identifier:\s*([^\s*]+)/)?.[1] ?? null,
      abi: artifactCopy,
      source: solidityCopy,
      notice: licenseCopy,
      importTest: {
        command: 'node node_modules/vitest/vitest.mjs run tests/unit/abi.test.ts',
        result: verified ? 'passed' : 'not-run-by-generator',
      },
    });
  }

  for (const [output, exports] of grouped) {
    const content = [
      '/* This file is generated by scripts/vendor-abis.mjs. Do not hand-edit ABI entries. */',
      "import type { Abi } from 'viem';",
      '',
      ...exports,
      '',
    ].join('\n');
    const path = join(root, output);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content);
  }

  const sdkSource = {
    id: 'uniswap-v4-sdk-pool-id-cross-check',
    packageName: '@uniswap/v4-sdk',
    version: '2.3.3',
  };
  const sdk = await readPackage(sdkSource.packageName);
  const sdkRoot = packageRoot(sdkSource.packageName);
  const [sdkPoolCopy, sdkNoticeCopy] = await Promise.all([
    copyUpstream(sdkSource, join(sdkRoot, 'dist/esm/src/entities/pool.js'), 'source.js'),
    copyUpstream(sdkSource, join(sdkRoot, 'LICENSE'), 'NOTICE_OR_LICENSE'),
  ]);
  evidence.push({
    id: 'uniswap-v4-sdk-pool-id-cross-check', package: '@uniswap/v4-sdk', version: sdk.version,
    packageLicense: sdk.license ?? null,
    sourceUrl: 'https://unpkg.com/@uniswap/v4-sdk@2.3.3/dist/esm/src/entities/pool.js',
    sourceSpdx: null, abi: null, source: sdkPoolCopy, notice: sdkNoticeCopy,
    importTest: {
      command: 'node node_modules/vitest/vitest.mjs run tests/unit/abi.test.ts',
      result: verified ? 'passed' : 'not-run-by-generator',
    },
  });
  evidence.push({
    id: 'lp-terminal-reference', package: 'labrinyang/lp-terminal', version: 'c127e70a2a21ca40f5668d155587e36e80049277',
    packageLicense: 'MIT', sourceUrl: 'https://github.com/labrinyang/lp-terminal/tree/c127e70a2a21ca40f5668d155587e36e80049277',
    sourceSpdx: null, abi: null, source: null, notice: null,
    importTest: 'reference only; no application code copied. Robinhood StateView candidate: 0xF3334192D15450CdD385c8B70e03f9A6bD9E673b (unverified).',
  });

  await mkdir(dirname(evidencePath), { recursive: true });
  await writeFile(evidencePath, `${JSON.stringify({ generatedAt: new Date().toISOString(), entries: evidence }, null, 2)}\n`);
}

await main();
